# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createQueueElement <- function(priority, additionalInfo) {
    .Call('_XDS_createQueueElement', PACKAGE = 'XDS', priority, additionalInfo)
}

getQueueElementInfo <- function(x) {
    .Call('_XDS_getQueueElementInfo', PACKAGE = 'XDS', x)
}

